/**
 * Live index/model state. Worth showing during judging: it proves the corpus is
 * real and makes the extractive-vs-LLM mode explicit rather than hidden.
 *
 * `effectiveModel` is the `used_model` reported by the most recent answer. It
 * takes precedence over the configured model, because a key being present does
 * not mean the API was actually reachable — showing "LLM: …" while answers were
 * really produced by the fallback would be misleading.
 */
export default function StatusBar({ stats, error, onRetry, effectiveModel, t }) {
  if (error) {
    return (
      <div className="status status--offline" role="status">
        <span className="status__dot status__dot--offline" />
        <span>
          {t("status.offline")} <code>uvicorn app.main:app --reload</code>
        </span>
        <button type="button" className="btn btn--ghost btn--sm" onClick={onRetry}>
          {t("status.retry")}
        </button>
      </div>
    );
  }

  if (!stats) {
    return (
      <div className="status" role="status">
        <span className="status__dot status__dot--pending" />
        <span>{t("status.connecting")}</span>
      </div>
    );
  }

  // A "fallback"/"extractive" used_model means the LLM did not actually serve
  // the answer, whatever the configuration claims.
  const degraded = effectiveModel
    ? /fallback|extractive/i.test(effectiveModel)
    : !stats.llm_enabled;
  const modelName = effectiveModel ?? stats.llm_model;

  return (
    <div className="status" role="status">
      <span className="status__dot status__dot--live" />

      {/* No "/ 23,461" here any more. That denominator is BIS's own published
          figure as of June 2025, and the live portal now returns 24,324 — so
          rendering the pair as a fraction read as though we had indexed more
          standards than exist. The Overview states both numbers with their
          dates, which is where the comparison belongs. */}
      <span className="status__item">
        <strong>{stats.indexed_standards.toLocaleString()}</strong> {t("status.indexed")}
      </span>
      <span className="status__sep" />

      <span className="status__item">
        <strong>
          {stats.departments_covered}/{stats.departments_total}
        </strong>{" "}
        {t("status.departments")}
      </span>
      <span className="status__sep" />

      <span className="status__item">
        <strong>{stats.qco_mandatory}</strong> {t("status.mandatory")}
      </span>
      <span className="status__sep" />

      <span
        className={`pill ${degraded ? "pill--extractive" : "pill--llm"}`}
        title={
          degraded
            ? `Answers come from the catalogue directly — ${
                effectiveModel ?? "no LLM key configured"
              }`
            : `Answers generated by ${modelName}`
        }
      >
        {degraded ? t("status.extractive") : `LLM: ${modelName}`}
      </span>
    </div>
  );
}
